<Project>
  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/corevar/cli-tools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/corevar/cli-tools</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
